# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔
  技术: /tags/技术

# SubNav
subnav:
  github: https://github.com/CrazyMilk
  zhihu: https://zhihu.com/people/CrazyMilk
  weibo: http://weibo.com/CatDrinkMilk
  #rss: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /assets/images/favicon/favicon.png

#你的头像url
avatar: /assets/images/avatar/avatar.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "CrazyMilk"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  JuniperPhoton: http://juniperphoton.net/
  yazoo: http://yazhuo.github.io/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 嗯...我是喵星人，我从火星来，任务是让你们猜不透~
